### ISSUE TITLE
Incorrect parser argument for model checkpoint loading

### ISSUE THREAD

**Issue by ndormann** [chmxu/eTT_TMLR2022#10]
There is a bug in the example code loading a pre-trained ViT model.
[Code Line](https://github.com/chmxu/eTT_TMLR2022/blob/8797433e7906d6d480f3bdd8b4ea6a20f15e5645/test_extractor_pa_vit_prefix.py#L47)
The argument should be "model.ckpt" instead of "data.ckpt".
This bug got introduced in commit "update doc"/2f15355

**Comment by chmxu** [comment]
Thank you. Let me check that. I don't expect this bug since this code is ok to run.

**Comment by chmxu** [comment]
Fine it's indeed a weird bug. Thank you again.
