### ISSUE TITLE
Request for support data finetuning code. 

### ISSUE THREAD

**Issue by karthikpullalarevu** [chmxu/eTT_TMLR2022#4]
Hello.
Could you please upload the finetuning code that was used for the support data. Also, I would like to implement this with SWIN_VIT. Could you give a brief methodology on what changes have to be made at model level, ie. how to implement DRA in the layers. 

Thanks.

**Comment by chmxu** [comment]
Hi,
The current released version contains the full pipeline during testing. The finetuning code is in `models/pa_prefix.py`, and the changes to the backbone including adapter and prefix are included in `models/vit_dino.py`. If you want to use Swin as backbone, you can just change the corresponding code in `models/vit_dino.py`, pretrain the model again using DINO on ImageNet meta-train set, and use our code to test the model.
