### ISSUE TITLE
About the the initialization of prefix

### ISSUE THREAD

**Issue by yiyuyuyi** [chmxu/eTT_TMLR2022#8]
Hello! Thank you for releasing your outstanding work! While using your code, I have a small question: In your paper, you emphasized the importance of the initial prefix, and you adopted the initialization method of the attentive prototype. However, the implementation in your code seems to be simply averaging all patch embeddings from each category. I wonder if there is a comparable performance between the two approaches? It appears that you provide a simpler option in your code.

**Comment by chmxu** [comment]
I'm not sure what you mean for simply averaging. Check https://github.com/chmxu/eTT_TMLR2022/blob/main/models/vit_dino.py#L381. 

As for the performance, we further find that fine-grained tuning of the hyper-parameters can also receive same effect of using better initialization.

**Comment by yiyuyuyi** [comment]
> I'm not sure what you mean for simply averaging. Check https://github.com/chmxu/eTT_TMLR2022/blob/main/models/vit_dino.py#L381.
> 
> As for the performance, we further find that fine-grained tuning of the hyper-parameters can also receive same effect of using better initialization.
Thank you！ And I truly apologize; it was my mistake, I should have been more attentive.
