### ISSUE TITLE
About the reproduction

### ISSUE THREAD

**Issue by teyouta** [chmxu/eTT_TMLR2022#9]
Hi, I am very interested in your work. When I attempted  to reproduce the model provided in #1 using the default settings in your code, I achieved an accuracy of 75.27% on Omniglot and 76.77% on Aircraft. This shows a notable difference from the results mentioned in your paper (78.11% and 79.94%). Could you please help me identify if there are any details I might have overlooked?

**Comment by chmxu** [comment]
Hi, I haven't been using this codebase recently. Jingshi will soon publish our code for TMLR23 paper [link](https://www.research.ed.ac.uk/files/394901097/Worst-case_Feature_LEI_DOA26102023_VOR_CC_BY.pdf). Hopefully this can solve your problem.

**Comment by teyouta** [comment]
> Hi, I haven't been using this codebase recently. Jingshi will soon publish our code for TMLR23 paper [link](https://www.research.ed.ac.uk/files/394901097/Worst-case_Feature_LEI_DOA26102023_VOR_CC_BY.pdf). Hopefully this can solve your problem.

Ok, thank you！
